# Linear Algebra for CpE
## Laboratory 4 : Vector Operations

Now that you have a fundamental knowledge about linear combination, we'll try to apply the fundamental operations

### Objectives
At the end of this activity you will be able to:
1. Referesh knowledge on vector operations while being familiar with new operations such as products.
2. Visualize vector operations.
3. Perform vector operations using Python.

## Discussion

In [243]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

We have dealt with some of the vector operations in the last module, now we will dwell into more operations. In this laboratory, we will tackle addition,multiplication,division and the inner product of a vector.

## Vector Addition

We have encountered vector before especially with your last activity. Vector addition is simply the element-wise addition of the scalar values of the vectors. Let's take the following vectors as a sample:

$$A = \begin{bmatrix}1\\2\\0\end{bmatrix}, B= \begin{bmatrix}3\\1\\-2 \end{bmatrix}$$

So if do a vector addition of these two vectors we'll get:

$$A + B = \begin{bmatrix}4\\3\\-2\end{bmatrix}$$

We can progammatically solve this using `np.add()` or simply using `+`.

In [244]:
A = np.array([1,2,0])
B = np.array([3,1,-2])

In [245]:
A+B

array([ 4,  3, -2])

In [246]:
np.add(A,B)

array([ 4,  3, -2])

## Vector Subtraction

Vector subtraction is similar to your vector addition but you would need to scale the second vector using a negative scalar that is usuall $-1$. So if we subtract vector $B$ from vector $A$ we get:

$$A-B = \begin{bmatrix}-2\\1\\2\end{bmatrix}$$

In Python, this can be achieved by using `np.subtract()` or `-`

In [247]:
np.subtract(A,B)

array([-2,  1,  2])

In [248]:
A-B

array([-2,  1,  2])

## Vector Multiplication

Vector multiplication, like addition does its operations element-wise. So basic vector multiplication can be achieved by multiplying the elements or the scalars of the vectors individually. So:
$$A * B = \begin{bmatrix}3\\2\\0\end{bmatrix}$$
We can implement this in code by using `np.multiply()` or simply operating with `*`.

In [249]:
np.multiply(A,B)

array([3, 2, 0])

In [250]:
A*B

array([3, 2, 0])

## Vector Division

Dividing a vector by another is uncommon, but if the situation specifies that each elements or scalars of the vector would be divided individually we can perform this by:
$$A./B = \begin{bmatrix}\frac{1}{3}\\2\\0\end{bmatrix}$$
Take note that the notation we used here is $./$ for element-wise division, this notation is based in a MATLab notation for element-wise division. This can be achieved in Python using `np.divide()` or `/`.

In [251]:
np.divide(A,B)

array([ 0.33333333,  2.        , -0.        ])

In [252]:
A/B

array([ 0.33333333,  2.        , -0.        ])

## Modulus of a Vector

The modulus of a vector or the magnitude of a vector can be determined using the Pythagorean theorem. Given the vector $A$ and its scalars denoted as $a_n$ where $n$ is the index of the scalar. So if we have:
$$A = \begin{bmatrix}1\\2\end{bmatrix}$$
We can compute the magnitude as:
$$||A|| = \sqrt{a_1^2 + a_2^2} = \sqrt{1^2 + 2^2} = \sqrt{5}$$
So if we have a matrix with more parameters such as:
$$B=\begin{bmatrix}2\\5\\-1\\0\end{bmatrix}$$
We can generalize the Pythagorean theorem to compute for the magnitude as:
$$||B|| = \sqrt{b_1^2 + b_2^2 + b_3^2 + ... +b_n^2} = \sqrt{\sum_{n=1}^{N}b_n^2}$$
And this equation is now called a Euclidian distance or the Euclidean Norm. We can implement this explicitly by for loops or using `np.linalg.norm()` to get the Euclidian Norm.

In [253]:
A = np.array([1,2])
B = np.array([2,5,-1,0])

In [254]:
np.linalg.norm(A)

2.23606797749979

In [255]:
np.linalg.norm(B)

5.477225575051661

## Vector Dot Product / Inner Product

The inner product of a vector is the sum of the products of each elements of the vectors. So given vectors $H$ and $G$ below:
$$H=\begin{bmatrix}1\\3\\6\end{bmatrix}, G = \begin{bmatrix}5\\2\\1\end{bmatrix}$$
We first take the element-wise product of the vectors:
$$H*G = \begin{bmatrix}5\\6\\6\end{bmatrix}$$
Then we take the sum of the products, making it the inner product of a vector:
$$H\cdot G = 17$$
You can solve for the inner product using an explicit function, `np.inner()` or the `@` operator.

In [256]:
H = np.array([1,3,6])
G = np.array([5,2,1])

In [257]:
np.inner(H,G)

17

In [258]:
H @ G

17

## Activity

### Task 1

Make an explicit function (not using any of NumPy's preset functions) solving the modulus of a vector using the Euclidian Norm formula: 
$$||X|| = \sqrt{\sum_{n=1}^{N}x_n^2}$$
Create a program flowchart for your algorithm and explain it in your methodology. Create 6 different vectors which their element count should not be lower than 4 elements. Explain the results at the results discussion section while comparing them to the `np.linalg.norm()` function.

In [259]:
import math
vect1 = np.array([1,2,3,4])
vect2 = np.array([6,5,4,3])
vect3 = np.array([0,2,4,6])
vect4 = np.array([10,8,6,4])                      
vect5 = np.array([1,3,5,7])
vect6 = np.array([11,9,7,5])

In [260]:
def my_euc_norm(list):
    # squares the elements
    square_elements = []
    sum_vect = 0
    for element in list:
        square_elements.append(element ** 2)
        
# # list comprehension version of the for loop
#     square_elements = [element ** 2 for element in list] 
#     print(square_elements)

    # gets the sum of the squared elements
    for elements in range(len(square_elements)):   
        sum_vect = sum_vect + square_elements[elements];  
    euc_norm = math.sqrt(sum_vect)
    return euc_norm
    
print("Euclidian Norm using my Function")
print("the euclidian norm of vector 1:",  my_euc_norm(vect1))
print("the euclidian norm of vector 2:",  my_euc_norm(vect2))
print("the euclidian norm of vector 3:",  my_euc_norm(vect3))
print("the euclidian norm of vector 4:",  my_euc_norm(vect4))
print("the euclidian norm of vector 5:",  my_euc_norm(vect5))
print("the euclidian norm of vector 6:",  my_euc_norm(vect6))

Euclidian Norm using my Function
the euclidian norm of vector 1: 5.477225575051661
the euclidian norm of vector 2: 9.273618495495704
the euclidian norm of vector 3: 7.483314773547883
the euclidian norm of vector 4: 14.696938456699069
the euclidian norm of vector 5: 9.16515138991168
the euclidian norm of vector 6: 16.61324772583615


In [261]:
# proving my function with numpy
def numpy_euclidian_norm(vect):
    numpy_euc_norm = np.linalg.norm(vect)
    return numpy_euc_norm

print("Euclidian Norm using Numpy Library")
print("the euclidian norm of vector 1:",  numpy_euclidian_norm(vect1))
print("the euclidian norm of vector 2:",  numpy_euclidian_norm(vect2))
print("the euclidian norm of vector 3:",  numpy_euclidian_norm(vect3))
print("the euclidian norm of vector 4:",  numpy_euclidian_norm(vect4))
print("the euclidian norm of vector 5:",  numpy_euclidian_norm(vect5))
print("the euclidian norm of vector 6:",  numpy_euclidian_norm(vect6))

Euclidian Norm using Numpy Library
the euclidian norm of vector 1: 5.477225575051661
the euclidian norm of vector 2: 9.273618495495704
the euclidian norm of vector 3: 7.483314773547883
the euclidian norm of vector 4: 14.696938456699069
the euclidian norm of vector 5: 9.16515138991168
the euclidian norm of vector 6: 16.61324772583615


### Task 2

Make an explicit function (not using any of NumPy's preset functions nor the `@` operator) solving the inner product of two vectors using the inner product formula: 
$$A\cdot B = \sum_{n=1}^{N} a_n \times b_n $$
$$whereas: N = len(A) = len(B)$$
Create a program flowchart for your algorithm and explain it in your methodology. Create 5 distinct pairs vectors which their element count should not be lower than 5 elements. Explain the results at the results discussion section while comparing them to the `np.inner()` function.

In [262]:
#1st pair
vect1 = np.array([2,5,4,3,4])                        
vect2 = np.array([8,4,6,7,5])  

#2nd pair
vect3 = np.array([8,7,4,6,9])
vect4 = np.array([8,4,5,1,6])       

#3rd pair
vect5 = np.array([8,4,5,2,3]) 
vect6 = np.array([2,6,4,5,6])   

#4th pair
vect7 = np.array([5,9,4,6,2])  
vect8 = np.array([4,8,8,5,8])

#5th pair
vect9 = np.array([5,7,8,5,4])                      
vect10 = np.array([6,5,4,9,8]) 

In [263]:
def my_dot_product(vec1, vec2):
    # multiplies the vector pairs
    multiply_pair = vec1*vec2
    # gets the sum of the multiply_pair
    sum_vect = 0
    for elements in range(len(multiply_pair)):    
        sum_vect = sum_vect + multiply_pair[elements]; 
    return(sum_vect)

print("Dot Product using my Function")
print("The dot product of vector 1 and vector 2:",  my_dot_product(vect1,vect2))
print("The dot product of vector 3 and vector 4:",  my_dot_product(vect3,vect4))
print("The dot product of vector 5 and vector 6:",  my_dot_product(vect5,vect6))
print("The dot product of vector 7 and vector 8:",  my_dot_product(vect7,vect8))
print("The dot product of vector 9 and vector 10:",  my_dot_product(vect9,vect10))

Dot Product using my Function
The dot product of vector 1 and vector 2: 101
The dot product of vector 3 and vector 4: 172
The dot product of vector 5 and vector 6: 88
The dot product of vector 7 and vector 8: 170
The dot product of vector 9 and vector 10: 174


In [264]:
# proving my function with numpy
def numpy_dot_product(vec1,vec2):
    numpy_dot_prod = np.inner(vec1, vec2)
    return numpy_dot_prod

print("Dot Product using Numpy Library")
print("The dot product of vector 1 and vector 2:", numpy_dot_product(vect1,vect2))
print("The dot product of vector 3 and vector 4:", numpy_dot_product(vect3,vect4))
print("The dot product of vector 5 and vector 6:", numpy_dot_product(vect5,vect6))
print("The dot product of vector 7 and vector 8:", numpy_dot_product(vect7,vect8))
print("The dot product of vector 9 and vector 10:", numpy_dot_product(vect9,vect10))


Dot Product using Numpy Library
The dot product of vector 1 and vector 2: 101
The dot product of vector 3 and vector 4: 172
The dot product of vector 5 and vector 6: 88
The dot product of vector 7 and vector 8: 170
The dot product of vector 9 and vector 10: 174


### Task 3

Code the following vector operation and solve them using the given vector values

$$ ((A^2 + B^2 + C^2) * (A * (B + A*B)./C))*||A + B + C||$$
$$A = \begin{bmatrix}-0.4\\0.3\\-0.6\end{bmatrix}, B = \begin{bmatrix}-0.2\\0.2\\1\end{bmatrix}, C = \begin{bmatrix}0.2\\0.1\\-0.5\end{bmatrix}$$

Create a program flowchart for your algorithm and explain it in your methodology. In your results, compare your answer to the expected output, visualize, and explain the resulting vector using a 3D plot.

In [265]:
A = np.array([-0.4,0.3,-0.6])
B = np.array([-0.2,0.2,1])
C = np.array([0.2,0.1,-0.5])
first_p = (A@A + B@B + C@C)
second_p = (A*(B+A*B)/C)
third_p = (np.linalg.norm(A+B+C))
final = first_p * second_p * third_p

print(final)

[0.34769805 1.13001866 0.6953961 ]


Expected answer: <br>
`array([0.34769805, 1.13001866, 0.6953961 ])`

## Conclusion guide

For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learn and achieved in this activity. 